import fs from 'fs-extra';
import path from 'path';
import { PROJECT_TYPES } from './detector.js';

/**
 * Dockerfile Generator
 * 
 * Generates optimized, multi-stage Dockerfiles based on project type
 */

const TEMPLATES = {
  // Next.js
  [PROJECT_TYPES.NEXTJS]: `# Auto-generated by Sidekick PaaS
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "server.js"]
`,

  // React (Vite/CRA) - Served with nginx
  [PROJECT_TYPES.REACT]: `# Auto-generated by Sidekick PaaS
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY --from=builder /app/build /usr/share/nginx/html 2>/dev/null || true
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`,

  // Vue.js
  [PROJECT_TYPES.VUE]: `# Auto-generated by Sidekick PaaS
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`,

  // Express.js
  [PROJECT_TYPES.EXPRESS]: `# Auto-generated by Sidekick PaaS
FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .
ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "index.js"]
`,

  // Generic Node.js
  [PROJECT_TYPES.NODEJS]: `# Auto-generated by Sidekick PaaS
FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .
ENV NODE_ENV=production
EXPOSE 3000
CMD ["npm", "start"]
`,

  // FastAPI
  [PROJECT_TYPES.PYTHON_FASTAPI]: `# Auto-generated by Sidekick PaaS
FROM python:3.11-slim AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.11-slim
WORKDIR /app
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY . .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
`,

  // Flask
  [PROJECT_TYPES.PYTHON_FLASK]: `# Auto-generated by Sidekick PaaS
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV FLASK_APP=app.py
ENV FLASK_ENV=production
EXPOSE 5000
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
`,

  // Django
  [PROJECT_TYPES.PYTHON_DJANGO]: `# Auto-generated by Sidekick PaaS
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN python manage.py collectstatic --noinput
EXPOSE 8000
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]
`,

  // Generic Python
  [PROJECT_TYPES.PYTHON]: `# Auto-generated by Sidekick PaaS
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["python", "app.py"]
`,

  // Go
  [PROJECT_TYPES.GO]: `# Auto-generated by Sidekick PaaS
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/main .
EXPOSE 8080
CMD ["./main"]
`,

  // Rust
  [PROJECT_TYPES.RUST]: `# Auto-generated by Sidekick PaaS
FROM rust:1.75 AS builder
WORKDIR /app
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/app /usr/local/bin/app
EXPOSE 8080
CMD ["app"]
`,

  // Static Site
  [PROJECT_TYPES.STATIC]: `# Auto-generated by Sidekick PaaS
FROM nginx:alpine
COPY . /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`
};

/**
 * Generate Dockerfile for a project
 * @param {string} projectType - Detected project type
 * @param {string} repoPath - Path to repository
 * @param {object} detection - Detection result with additional info
 */
export async function generateDockerfile(projectType, repoPath, detection = {}) {
  const template = TEMPLATES[projectType];
  
  if (!template) {
    throw new Error(`No Dockerfile template for project type: ${projectType}`);
  }
  
  let dockerfile = template;
  
  // Customize based on detection
  if (detection.startCommand && projectType === PROJECT_TYPES.NODEJS) {
    dockerfile = dockerfile.replace(
      'CMD ["npm", "start"]',
      `CMD ${JSON.stringify(detection.startCommand.split(' '))}`
    );
  }
  
  // Write Dockerfile
  const dockerfilePath = path.join(repoPath, 'Dockerfile.sidekick');
  await fs.writeFile(dockerfilePath, dockerfile);
  
  return dockerfilePath;
}

/**
 * Generate .dockerignore file
 */
export async function generateDockerignore(repoPath) {
  const content = `# Auto-generated by Sidekick PaaS
node_modules
npm-debug.log
.git
.gitignore
.env
.env.*
*.md
.vscode
.idea
coverage
.nyc_output
*.log
__pycache__
*.pyc
.pytest_cache
.tox
.venv
venv
.mypy_cache
`;

  const ignorePath = path.join(repoPath, '.dockerignore');
  
  // Don't overwrite if exists
  if (!await fs.pathExists(ignorePath)) {
    await fs.writeFile(ignorePath, content);
  }
  
  return ignorePath;
}

/**
 * Get port for project type
 */
export function getDefaultPort(projectType) {
  const ports = {
    [PROJECT_TYPES.NEXTJS]: 3000,
    [PROJECT_TYPES.REACT]: 80,
    [PROJECT_TYPES.VUE]: 80,
    [PROJECT_TYPES.EXPRESS]: 3000,
    [PROJECT_TYPES.NODEJS]: 3000,
    [PROJECT_TYPES.PYTHON_FASTAPI]: 8000,
    [PROJECT_TYPES.PYTHON_FLASK]: 5000,
    [PROJECT_TYPES.PYTHON_DJANGO]: 8000,
    [PROJECT_TYPES.PYTHON]: 8000,
    [PROJECT_TYPES.GO]: 8080,
    [PROJECT_TYPES.RUST]: 8080,
    [PROJECT_TYPES.STATIC]: 80
  };
  return ports[projectType] || 3000;
}
