import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const NGINX_CONF_DIR = process.env.NGINX_CONF_DIR || path.join(__dirname, '../../data/nginx');
const BASE_DOMAIN = process.env.BASE_DOMAIN || 'localhost';

/**
 * Nginx Configuration Service
 * 
 * Generates and manages nginx reverse proxy configs
 */

/**
 * HTTP-only config template (before SSL)
 */
const HTTP_TEMPLATE = `# Auto-generated by Sidekick PaaS
# Project: {{PROJECT_NAME}}

server {
    listen 80;
    server_name {{DOMAIN}};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://{{UPSTREAM}};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 86400;
    }
}
`;

/**
 * Full HTTPS config template (after SSL)
 */
const HTTPS_TEMPLATE = `# Auto-generated by Sidekick PaaS
# Project: {{PROJECT_NAME}}

server {
    listen 80;
    server_name {{DOMAIN}};
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name {{DOMAIN}};

    ssl_certificate /etc/letsencrypt/live/{{DOMAIN}}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{DOMAIN}}/privkey.pem;
    
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256;
    
    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    
    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied any;
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/json application/xml;
    
    # Rate limiting
    limit_req_zone $binary_remote_addr zone={{PROJECT_ID}}:10m rate=10r/s;
    
    location / {
        limit_req zone={{PROJECT_ID}} burst=20 nodelay;
        
        proxy_pass http://{{UPSTREAM}};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 86400;
        
        # WebSocket support
        proxy_connect_timeout 7d;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;
    }
}
`;

/**
 * Generate nginx config for a project
 * @param {string} projectId - Project ID
 * @param {object} options - Configuration options
 */
export async function generateConfig(projectId, options) {
  const {
    name,
    subdomain,
    hostPort,
    ssl = false
  } = options;
  
  const domain = `${subdomain}.${BASE_DOMAIN}`;
  const upstream = `127.0.0.1:${hostPort}`;
  
  // Choose template based on SSL status
  const template = ssl ? HTTPS_TEMPLATE : HTTP_TEMPLATE;
  
  // Replace placeholders
  const config = template
    .replace(/{{PROJECT_NAME}}/g, name)
    .replace(/{{PROJECT_ID}}/g, projectId)
    .replace(/{{DOMAIN}}/g, domain)
    .replace(/{{UPSTREAM}}/g, upstream);
  
  // Ensure directory exists
  await fs.ensureDir(NGINX_CONF_DIR);
  
  // Write config file
  const configPath = path.join(NGINX_CONF_DIR, `${projectId}.conf`);
  await fs.writeFile(configPath, config);
  
  return {
    path: configPath,
    domain,
    ssl
  };
}

/**
 * Remove nginx config for a project
 */
export async function removeConfig(projectId) {
  const configPath = path.join(NGINX_CONF_DIR, `${projectId}.conf`);
  
  if (await fs.pathExists(configPath)) {
    await fs.remove(configPath);
    return true;
  }
  
  return false;
}

/**
 * Test nginx configuration
 */
export async function testConfig() {
  try {
    await execAsync('nginx -t');
    return { valid: true };
  } catch (error) {
    return { valid: false, error: error.message };
  }
}

/**
 * Reload nginx
 */
export async function reloadNginx() {
  try {
    await execAsync('nginx -s reload');
    return { success: true };
  } catch (error) {
    return { success: false, error: error.message };
  }
}

/**
 * Get all generated configs
 */
export async function listConfigs() {
  await fs.ensureDir(NGINX_CONF_DIR);
  
  const files = await fs.readdir(NGINX_CONF_DIR);
  return files.filter(f => f.endsWith('.conf')).map(f => ({
    projectId: f.replace('.conf', ''),
    path: path.join(NGINX_CONF_DIR, f)
  }));
}

/**
 * Enable SSL for a project (after certbot)
 */
export async function enableSSL(projectId, options) {
  return generateConfig(projectId, { ...options, ssl: true });
}

export { BASE_DOMAIN };
